### PR TITLE
Fix transpose typos in additive functional lecture

### PR DESCRIPTION
**Pull request by jmbejara**
It looks like there are some typos in the formulas for the decomposition. Matrices don't conform. I've fixed them in this PR. Hope this looks ok. Great lectures, btw!

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @jmbejara !  All feedback & PRs are appreciated.

@shizejin, might you be able to review this or request someone else?

**Comment by shizejin** [comment]
@jstac Sure I would love to review this. I'll do this today.

**Comment by shizejin** [comment]
Hi @jmbejara, thank you so much for spotting these typos. It is true that the formulas for H and g matrices are not correct. Specifically, I observed inconsistency of shapes of D, F, H, and g matrices in the lecture, which I think is what causes the problem that you very sharply pointed out.

If we stick to the dimensions of D and F as in equation (2), then the modifications you made is correct. [Here](https://nbviewer.jupyter.org/github/shizejin/Notebooks/blob/master/Derivation%20of%20Hansen-Scheinkman%20decomposition.ipynb) I derived H and g matrices with details.

It turns out that there are more corrections to make in addition to what you pointed out:

- [ ] change D' to D: [line162](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L162), [line817](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L817)

- [ ] change F' to F: [line170](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L170), [line831](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L831)

- [ ] change A' to A: [line766](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L766)

- [ ] change H' to H: [line832](https://github.com/QuantEcon/lecture-python-advanced/blame/master/source/rst/additive_functionals.rst#L831)

It would be great to have your opinions about how to complete this correction! @jstac @jmbejara

**Comment by jmbejara** [comment]
@shizejin Ok. You're right. I missed those. I've made those additional changes and amended the original commit. I also made one more change to line 1044 (changing A' to A). Thanks!

**Comment by jstac** [comment]
Thanks guys!  Looks good.  @mmcky, I see this is failing due to checking out of QE theme.  What should we do here?

**Comment by mmcky** [comment]
@jstac after searching and doing some debug work (i.e. reseting security keys etc) it has dawned on me what the issue is. It will need a bit more work to solve so I will raise an issue. Please go ahead and merge -- if you would like an `html` preview I can switch off the theme step. 

The issue here is when the theme files are fetched from a private repo -- the commit author is @jmbejara and a `404` is returned from GitHub.

**Comment by jstac** [comment]
Roger that @mmcky and thanks all.  This is greatly appreciated.

**Pull request merged**
