### PR TITLE
RFC: Update the AMSS lectures

### LINKED ISSUE #206: [amss] Broken from change to opt_tax_recur
@shizejin @QBatista it looks like there were some files updated by `opt_tax_recur` that have caused `amss` execution  to fail.

Would you be able to put a PR in for `amss` to fix the missing imports?

http://preview.python-advanced.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/amss.html

### PR DESCRIPTION
**Pull request by QBatista**
Refactor the code in the AMSS lectures to improve speed through just-in-time compilation and the code structure.

Three lectures need to be modified:

- [x] `amss`
- [x] `amss2`
- [x] `amss3`

Close #206 #203

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @QBatista -- can you ping me with a review request when you want this merged?

Then I will `merge`, `make live`, and `migrate` this to the new `myst` repo as well.

**Comment by QBatista** [comment]
@mmcky Sure!

**Comment by mmcky** [comment]
> @mmcky Sure!

@QBatista no pressure -- just for planning purposes -- do you have an estimated timeline for these updates? 

Just thinking about when to migrate to the `jupyter-book` version :-)

**Comment by QBatista** [comment]
@mmcky Hopefully I should be done within a few days.

**Comment by mmcky** [comment]
thanks @QBatista

**Comment by QBatista** [comment]
@mmcky This is ready for merging.

**Comment by mmcky** [comment]
🎉 -- wow thanks for your help with this @QBatista. I'll merge now  and it will build overnight on the build server. 

Then I will migrate to `lecture-python.myst` in the morning

**Pull request merged**
