### PR TITLE
[migrate] update tomyst compatibility and tidy up some math

### PR DESCRIPTION
**Pull request by mmcky**
This PR does some tidy up of `math` for improved compatibility with `sphinx-tomyst`

It also implements changes suggested in: https://github.com/QuantEcon/lecture-python-advanced.myst/pull/21

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] to be reviewed by @shlff

**Comment by shlff** [comment]
Thanks @mmcky . I checked all lectures in the preview but always see the following message:

Screen Shot 2021-04-21 at 1 31 31 pm

I am wondering whether it is because the preview is invalid.

**Review by shlff — COMMENTED** [review]
Thanks @mmcky . I checked all changes in the preview against our live lectures one by one and can confirm that there is no difference between. 

I think it might be ready to merge.

**Comment by mmcky** [comment]
thanks @shlff

I appreciate the review.

**Pull request merged**
