### PR TITLE
reorganized

### PR DESCRIPTION
**Pull request by jstac**
This is a fairly major reorganization of the TOC, similar to https://github.com/QuantEcon/lecture-python-intro/pull/67.

It might break some links but sphinx stopped warning me about them after one or two runs.  Links need to be checked.

### CODE REVIEW

**Comment by mmcky** [comment]
hey @jstac for some reason `sphinx` stops warning you after the first run. So the only way to recover all `warnings` is to run `make clean` first.  I will check the logs now.

**Comment by jstac** [comment]
Thanks @mmcky .  @shizejin might be willing to help get this done.

**Comment by mmcky** [comment]
So there is a bug in the way we trigger `sphinx` on `travis`. We look for changed files and it appears the ones that are `deleted` appear as changed from our git call causing sphinx to fail when it can't find them. 

```
__main__.py: error: cannot find files ['source/rst/career.rst', 'source/rst/coleman_policy_iter.rst', 'source/rst/egm_policy_iter.rst', 'source/rst/ifp.rst', 'source/rst/index_dynamic_programming.rst', 'source/rst/index_intro_dynam.rst', 'source/rst/jv.rst', 'source/rst/odu.rst', 'source/rst/optgrowth.rst', 'source/rst/optgrowth_fast.rst', 'source/rst/wald_friedman.rst']
```

This is only an issue for complete deletion (rather than deletion within the document). Hmm ...

**Comment by mmcky** [comment]
**Broken Links**

[discrete_dp]

(line  236) broken    https://python-intro.quantecon.org/finite_markov.html#finite_dp_stoch_mat - Anchor 'finite_dp_stoch_mat' not found
1234(line  253) broken    https://python-intro.quantecon.org/finite_markov.html#finite_mc_expec - Anchor 'finite_mc_expec' not found

(line  788) broken    https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
1242(line  799) broken    https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html

(line 1120) broken    https://lectures.quantecon.org/py/optgrowth.html#Exercise-1 - Anchor 'Exercise-1' not found

**Comment by shizejin** [comment]
@jstac @mmcky I will try to see if I can help with this.

**Comment by mmcky** [comment]
thanks @shizejin -- we will merge this PR but I will open issues (with items listed above)

**Pull request merged**
