### PR TITLE
fixes anchors finite_mc_expec, finite_dp_stoch_mat and …

### LINKED ISSUE #94: [discrete_dp] broken links
```
writing output... [ 27%] discrete_dp
(line  255) broken    https://python-intro.quantecon.org/finite_markov.html#finite_mc_expec - Anchor 'finite_mc_expec' not found
(line  238) broken    https://python-intro.quantecon.org/finite_markov.html#finite_dp_stoch_mat - Anchor 'finite_dp_stoch_mat' not found
(line 1127) broken    https://lectures.quantecon.org/py/optgrowth.html#Exercise-1 - Anchor
```

### PR DESCRIPTION
**Pull request by najuzilu**
… update optgrowth url

fixes #94

### CODE REVIEW

**Comment by najuzilu** [comment]
Waiting for latest version of master in [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro) to display `optgrowth` lecture.  Travis will check fail for `optgrowth` since the lecture is not available.

**Comment by mmcky** [comment]
@najuzilu were there two PR's for `discrete_dp`?

**Comment by mmcky** [comment]
this has a merge conflict that will need to be resolved

**Comment by mmcky** [comment]
can you ping me once this merge conflict is resolved. Thanks.

**Comment by najuzilu** [comment]
I'm working on resolving the conflict now.

**Comment by najuzilu** [comment]
@mmcky Travis check fails because `optgrowth` is not live on our website yet.

**Comment by mmcky** [comment]
@najuzilu in the testing I don't understand why these links are failing now:

```
(line  789) broken    https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
1226(line  800) broken    https://python-intro.quantecon.org/optgrowth.html - 404 Client Error: Not Found for url: https://python-intro.quantecon.org/optgrowth.html
1227(line 1121) broken    https://python-intro.quantecon.org/optgrowth.html#Exercise-1 - Anchor 'Exercise-1' not found
```

**Comment by najuzilu** [comment]
That's strange. Does the order of execution matter? So, did you build the advanced lectures first and then the intro lectures?

**Comment by mmcky** [comment]
I am not sure `travis` is re-running. Looking into this now.

**Comment by mmcky** [comment]
ok so I think `travis` has been fixed now. thanks @najuzilu

**Pull request merged**
